name: Deploy bundle (dev)

on:
  push:
    branches: [dev]


jobs:
  deploy:
    name: Deploy to dev
    runs-on: ubuntu-latest
    environment: dev

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate bundle
        run: databricks bundle validate -t dev

      - name: Deploy bundle (dev)
        run: databricks bundle deploy -t dev
